spring:
  application:
    name: customer-service
  data:
    mongodb:
      uri: mongodb://root:MongoDB2025!@localhost:27017/customer-service?authSource=admin
      database: customer-service
      auto-index-creation: true
      uuid-representation: standard

server:
  port: 8080

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    br.matosit.customer_service: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always 