apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-service-config
  namespace: development
data:
  APPLICATION_NAME: "customer-service"
  SPRING_PROFILES_ACTIVE: "development"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_BR_MATOSIT: "DEBUG"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customer-service-config
  namespace: production
data:
  APPLICATION_NAME: "customer-service"
  SPRING_PROFILES_ACTIVE: "production"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_LEVEL_BR_MATOSIT: "INFO" 