apiVersion: v1
kind: Secret
metadata:
  name: customer-service-secrets
  namespace: development
type: Opaque
data:
  # Valores em base64 - Substitua com valores reais
  MONGODB_URI: bW9uZ29kYjovL3Jvb3Q6TW9uZ29EQjIwMjUhQGN1c3RvbWVyLXNlcnZpY2UtZGV2LW1vbmdvZGI6MjcwMTcvY3VzdG9tZXItc2VydmljZT9hdXRoU291cmNlPWFkbWlu
---
apiVersion: v1
kind: Secret
metadata:
  name: customer-service-secrets
  namespace: production
type: Opaque
data:
  # Valores em base64 - Substitua com valores reais
  MONGODB_URI: bW9uZ29kYjovL3Jvb3Q6TW9uZ29EQjIwMjUhQGN1c3RvbWVyLXNlcnZpY2UtcHJvZC1tb25nb2RiOjI3MDE3L2N1c3RvbWVyLXNlcnZpY2U/YXV0aFNvdXJjZT1hZG1pbg== 