
name: Feature Branch Validation

on:
  push:
    branches:
      - 'feature/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Unit Tests
        run: mvn test

      - name: Run Security Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'table'
          severity: 'CRITICAL,HIGH'

      - name: Install Git LFS
        run: git lfs install

      - name: Configure Git User
        run: |
          git config --global user.email "luismatos000@gmail.com"
          git config --global user.name "Luis Matos"

      - name: Track large files with Git LFS
        run: |
          git lfs track ".cache/trivy/db/trivy.db"
          git add .gitattributes
          git add .cache/trivy/db/trivy.db
          git commit -m "Track large file with Git LFS"

      - name: Create Pull Request
        if: success()
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          title: 'feat: ${{ github.ref_name }}'
          body: |
            ## Descrição
            Pull Request automático criado a partir da branch ${{ github.ref_name }}

            ## Checklist de Validação
            - ✅ Testes unitários passaram
            - ✅ Análise de segurança concluída

            Por favor, revise as alterações e aprove se estiver tudo correto.
          base: 'develop'
          branch: ${{ github.ref_name }}
          draft: false
          labels: |
            automated-pr
            feature
